# Hello, I just made this UHCRun for fun.
# I am going to improve some things in the future.
# I hope you will like it!
# If you have problem contact me: www.florixak.tk

# Expand plugins
use-Vault: true
use-LuckPerms: true

# Game
waiting-world: "waiting-lobby"
game-world: "world"
ending-world: "ending-lobby"
auto-map-reset: true
developer-mode: false

min-players-to-start: 2

starting-warning-time: 10 # start at <_> seconds

starting-countdown: 20 # seconds
mining-countdown: 15 # seconds
fighting-countdown: 15 # seconds
deathmatch-countdown: 60 # seconds
ending-countdown: 15 # seconds

teleport-after-mining: false

auto-broadcast:
  enabled: false
  random-messages: true
  interval: 360 # seconds

rewards-per-time:
  enabled: false
  money: 10
  level-xp: 20
  interval: 60

player-level:
  enabled: true
  level-xp-per-win: 500
  level-xp-per-lose: 100
  level-xp-per-kill: 50

string-coins: 0.0
coins-per-kill: 20
coins-per-win: 450
coins-per-lose: 100

gg-reward:
  coins: 30
  level-xp: 50

arrow-hit-hp: true

custom-ore-drops: true
random-drops: false # in development

xp-per-coal-ore: 20
xp-per-iron-ore: 60
xp-per-gold-ore: 100
xp-per-redstone-ore: 120
xp-per-lapis-ore: 120
xp-per-emerald-ore: 250
xp-per-diamond-ore: 130
xp-per-gravel: 10

lobby-items:
  kits:
    enabled: true
    always-buy: false
    display-name: "&fKits"
    material: NETHER_STAR
    slot: 0
  perks:
    enabled: true
    always-buy: false
    display-name: "&fPerks"
    material: ARROW
    slot: 1
  start:
    display-name: "&fStart"
    material: DIAMOND
    slot: 4
  vote:
    enabled: false
    display-name: "&fVote"
    material: PAPER
    slot: 3
  custom-crafts:
    enabled: true
    display-name: "&fCustom Crafts"
    material: CRAFTING_TABLE
    slot: 7
  statistics:
    display-name: "&fStatistics"
    slot: 8

spectator-items:
  spectator:
    enabled: true
    display-name: "&fTeleporter"
    material: COMPASS
    slot: 0
  leave:
    enabled: true
    display-name: "&cLeave"
    material: RED_BED
    slot: 8

border:
  size: 450
  damage: 1 # 2 = 1 HP, 4 = 2 HP ... 40 = 10HP
  warning-distance: 10 # blocks
  speed: 0.2 # blocks per second

# MySQL database
MySQL:
  enabled: false
  host: "167.86.104.34"
  port: "3306"
  database: "s93_uhcrun"
  username: "u93_OzwcaKVTCJ"
  password: "VQou=xt@gDOVCE.45c2qLl+w"