# Hello, I have just made this UHCRun plugin for fun.
# I am going to improve some things in the future.
# I hope you will like it!
# If you have problem contact me: www.florixak.tk

# This is main configuration file of UHCRun

settings:

  # Expand plugins
  addons:
    use-Vault: false
    use-LuckPerms: false
    use-ProtocolLib: true
    use-PlaceholderAPI: true

  # Game
  game:
    game-world: "world"
    auto-map-reset: true

    min-players-to-start: 2

    teleport-after-mining: false
    warning-time-at: 10 # start at <_> seconds

    enable-deathmatch: true

    # Countdowns
    countdowns:
      starting: 20 # seconds
      mining: 120 # seconds
      fighting: 120 # seconds
      deathmatch: 60 # seconds
      ending: 15 # seconds

    projectile-hit-hp: true

    custom-ore-drops: true
    random-drops: false # in development

  # Border
  border:
    size: 450 # <..> x <..>
    damage: 1 # 2 = 1 HP, 4 = 2 HP ... 40 = 10HP
    warning-distance: 10 # blocks
    speed: 0.2 # blocks per second

  # Teams
  teams:
    team-mode: true
    max-size: 3
    friendly-fire: false

  # Rewards
  rewards:
    kill:
      money: 30
      exp: 60
      player-exp: 60
    win:
      money: 150
      player-exp: 300

  # Tablist
  tablist:
    # Works only with ProtocolLib
    enabled: true
    header: "&2&lUHC&a&lRun"
    footer: "\n&8www.florixak.tk"

  # Auto broadcast
  auto-broadcast:
    enabled: false
    random-messages: true
    period: 10 # seconds

  # Rewards per play time
  rewards-per-time:
    enabled: false
    money: 10
    player-exp: 20
    period: 60

  # Statistics
  statistics:
    # Players will gain their kills and deaths on game end
    add-on-game-ends: true

    player-level:
      # Players will gain xp and increase their level
      enabled: true

  # Economy
  economy:
    string-coins: 0.0

  # Custom nick
  custom-nick:
    enabled: true
    min-chars: 4 # < x

  # Selectors
  selectors:
    teams:
      enabled: true
      display-name: "&fTeams"
      material: NETHER_STAR
      slot: 0
    kits:
      enabled: true
      always-buy: false
      display-name: "&fKits"
      material: IRON_PICKAXE
      slot: 3
    perks:
      enabled: true
      always-buy: false
      display-name: "&fPerks"
      material: ARROW
      slot: 5
    custom-crafts:
      enabled: true
      display-name: "&fCustom Crafts"
      material: CRAFTING_TABLE
      slot: 4
    statistics:
      enabled: true
      display-name: "&fStatistics"
      material: PAPER # if null then player head
      slot: 8

  # MySQL database
  MySQL:
    enabled: false
    host: "localhost"
    port: "3306"
    database: ''
    username: ''
    password: ''

  # Chat
  chat:
    # %player% - Name of player
    # %luckperms-prefix% - If luckperms are allowed in config, displays player prefix
    # %message% - Sent message
    # %level% - Player level

    format: "%level% &f%luckperms-prefix% %team% %player% &7» &f%message%"
    level-with-brackets: true

    blocked-commands:
      - /pl
      - /plugins
      - /lp
      - /lp help
      - /lp editor
      - /luckperms
      - /luckperms editor
      - /luckperms help
      - /paper
      - /plugins
      - /paper
      - /plugins
      - /paper
      - /gm
      - /gmc
      - /gms
      - /gmsp
      - /gma
      - /gamemode
      - /gamemode 0
      - /gamemode 1
      - /gamemode 2
      - /gamemode 3
      - /gamemode c
      - /gamemode s
      - /gamemode a
      - /gamemode sp
      - /gamemode creative
      - /gamemode survival
      - /gamemode adventure
      - /gamemode spectator
      - /gm c
      - /gm s
      - /gm a
      - /gm sp
      - /gm spec
      - /give
      - /kill
      - /?