name: UHCRun
version: '${project.version}'
main: me.florixak.uhcrun.UHCRun
api-version: 1.18
authors: [ FloriXak ]
softdepend: [ Vault, LuckPerms, PlaceholderAPI ]

commands:
  workbench:
  wb:
  anvil:
  nick:
  unnick:
