name: UHCRun
version: '${project.version}'
main: me.florixak.uhcrun.UHCRun
api-version: 1.19
authors: [ FloriXak ]
softdepend: [ ProtocolAPI, Vault, LuckPerms, PlaceholderAPI ]

commands:
  forcestart:
    aliases: [ start ]
    description: Force game start
  workbench:
    aliases: [ wb, craftingtable ]
    description: Opens remotely workbench
  anvil:
    description: Opens remotely anvil
  nick:
    description: Use custom nick
  unnick:
    description: Reset custom nick
  team:
    aliases: [ teams ]
    description: Opens teams gui
